### ISSUE TITLE
Glispa Ad failed

### ISSUE THREAD

**Issue by gmartinsribeiro** [ampiri/ampiri-android-sdk#3]
Hello, I've got the following error:

09-13 10:44:24.685 28668-28668/cm.aptoidetv.pt I/Ampiri_SDK: Created NATIVE banner: 
                                                             with banner ID: 68f303aa-142f-498e-9c65-9fa0908a0062
                                                             with banner size: BANNER_SIZE_INTERSTITIAL
09-13 10:44:24.685 28668-28668/cm.aptoidetv.pt I/Ampiri_SDK: Loading banner ID: 68f303aa-142f-498e-9c65-9fa0908a0062
09-13 10:44:24.685 28668-28668/cm.aptoidetv.pt I/Ampiri_SDK: Banner state is [INITIAL]
09-13 10:44:25.285 28668-28668/cm.aptoidetv.pt I/Ampiri_SDK: Ad from [glispa] network is start load
09-13 10:44:25.505 28668-28668/cm.aptoidetv.pt I/Ampiri_SDK: Ad from [glispa] network is failed to load

Can someone explain me if I'm doing something wrong?

**Comment by viacheslavleonov** [comment]
Hi, could you please contact our Support team by email to support@ampiri.com?

**Comment by glispa-hyemin** [comment]
Hello, gmartinsribeiro :) Thanks for your feedback! Just to let you know that you will get faster response regarding technical issues like SDKs if you use the email, support@ampiri.com 

We need to identify what the exact cause of your issue first to resolve it. Could you please provide us the information below?

- The SDK version
- The version of mobile OS
- A description of the issue
- Step-by-step details on how to reproduce the issue/error
- The frequency of the issue (how often does this occur? repeatedly or once?)
-Any applicable Logs /error messages for ad request
- The SDK integration code (if relevant)
- Screenshots are always helpful, but optional!

Best Regards,
Ampiri Support
